version: '3'

services:
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - backend

networks:
    backend:
        driver: bridge